### ISSUE TITLE
Droits et notifications

### ISSUE THREAD

**Issue by benel** [UTT-GL03/helios#2]
Bonjour @evebrnd 

N'oubliez pas de définir dans votre entrepôt un rôle pour votre camarade de binôme, de manière à ce qu'elle puisse contribuer mais également être notifiée lorsque je vous fais des recommandations.

Merci d'avance.

**Comment by evebrnd** [comment]
Bonjour @benel 

C'est noté et fait, @Eflii est désormais administrateur du projet.
Merci pour la recommandation
